development: &defaults
  adapter: postgresql
  database: alasocho
  encoding: utf8
  username: root
  password:
  host: localhost
  min_messages: warning

test:
  << : *defaults
  database: alasocho_test

production:
  << : *defaults
