#!/usr/bin/env ruby
require 'rubygems'
require 'bundler'
Bundler.setup

require 'daemons'

pid_dir  = File.expand_path(File.dirname(__FILE__) + '/../tmp/pids')

Daemons.run_proc('resque_worker', dir_mode: :normal, dir: pid_dir, log_output: true) do
  require 'resque'

  worker = nil
  queues = (ENV['QUEUES'] || ENV['QUEUE'] || "*").to_s.split(',')

  begin
    worker = Resque::Worker.new(*queues)
    worker.verbose = ENV['LOGGING'] || (ENV['VERBOSE'] || 1)
    worker.very_verbose = ENV['VVERBOSE']
  rescue Resque::NoQueueError
    abort "set QUEUE env var, e.g. $ QUEUE=critical,high rake resque:work"
  end

  worker.log "Starting worker #{worker}"
  worker.work(ENV['INTERVAL'] || 5) # interval, will block
end
